allowBuilds:
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@triggerix/core'
  - '@triggerix/editor'
  - '@triggerix/registry'
shellEmulator: true

trustPolicy: no-downgrade
